# Generated by Django 3.1.6 on 2021-03-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210220_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sourceName',
            field=models.CharField(default='Dana', max_length=64),
        ),
    ]
