# Generated by Django 3.1.6 on 2021-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210312_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='fixme', max_length=64),
            preserve_default=False,
        ),
    ]
