# Generated by Django 3.1.6 on 2021-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210312_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tries',
            field=models.IntegerField(default=1),
        ),
    ]
